name: Deploy Docker images 至虛擬主機

on:
  push:
    branches:
      - feature/action-docker # 觸發條件為推送到 docker 分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Create .env file
      run:
        echo VARIABLE=${{ secrets.ENV_VARIABLE }} >> .env

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ironman-app-2023:amd64:latest

    - name: 更新 known_hosts 文件
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.HOST_NAME }} >> ~/.ssh/known_hosts

    - name: Create directory if not exists
      run: ssh root@${{ secrets.HOST_NAME }} "mkdir -p ~/websample/node-env"

    - name: Transfer .env file
      run: scp .env root@${{ secrets.HOST_NAME }}:~/websample/node-env/

    - name: Deploy to Docker
      run: 
        ssh root@${{ secrets.HOST_NAME }} '
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}ironman-app-2023-amd64:latest
          docker rm -f github-ac-sample || true
          docker run -d -p 3003:3000 --name github-ac-sample --env-file #HOME/websample/node-env/.env ${{ secrets.DOCKER_HUB_USERNAME }}/ironman-app-2023-amd64:latest
        '




        
      

        
        
